### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Electrik-rich546456** [emilegill743/grocery-delivery-project#1]
Hello I'm very new to python but thought this would be a nice idea but i am receiving a type error for the postcode

I wanted it to run from my pc ubuntu 19 so i removed the '`os.enviro'` and Heroku but  how do I integrate personal info into variables in that single file.??

Also why is the "import pandas as pd" there and not used. What is it for?? how do i use it ??

error 1
```
raise KeyError(key) from None
KeyError: 'POSTCODE'
```

error 2

line 21, in <module>
    "service_address" : {"postcode" : "postcodde "['POSTCODE'],

**Comment by emilegill743** [comment]
Hey @Electrik-rich546456 ,

The `os.environ[variable]` statements are purely to hide personal information that shouldn't be visible publicly. The easiest thing to do if you are running this locally and don't need to worry about exposing this information is to replace these statements with a variable- in the same way that I specify the `start_date` and `end_date` parameters.

I.e.
```
postcode = [insert your postcode here as a string]
latitude = [insert your latitude here as a string]
longitude = [insert your longitude here as a string]
account_id = [insert your act id here as a string]

json_data = {"requestorigin" : "gi",
             "data" : {"service_info" : {"fulfillment_type" : "DELIVERY",
                                         "enable_express" : 'false'},
                       "start_date" : start_date,
                       "end_date" : end_date,
                       "reserved_slot_id" : "",
                       "service_address" : {"postcode" : postcode,
                                            "latitude" : latitude,
                                            "longitude" : longitude},
                        "customer_info" : {"account_id" : account_id},
                        "order_info" : {"order_id" : "20983571638",
                                        "restricted_item_types" : [],
                                        "volume" : 0,"weight" : 0,
                                        "sub_total_amount" : 0,
                                        "line_item_count" : 0,
                                        "total_quantity" : 0}}}
```

You're absolutely right about `pandas` I must have been using it in a previous commit, but it's redundant now. I've just removed it now to avoid confusion.
